version = 0.1
[default.deploy.parameters]
stack_name = "s3-gsheets-exporter"
resolve_s3 = true
s3_prefix = "s3-gsheets-exporter"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
